package de.uol.swp.client.auth;

import com.google.common.eventbus.Subscribe;
import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXPasswordField;
import com.jfoenix.controls.JFXTextField;
import de.uol.swp.client.AbstractPresenter;
import de.uol.swp.client.auth.events.ShowLoginViewEvent;
import de.uol.swp.client.register.event.ShowRegistrationViewEvent;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;


/**
 * Manages the login window
 *
 * @author Marco Grawunder
 * @see de.uol.swp.client.AbstractPresenter
 * @since 2019-08-08
 */
public class LoginPresenter extends AbstractPresenter {

    public static final String FXML = "/fxml/LoginView.fxml";

    private static final ShowRegistrationViewEvent SHOW_REGISTRATION_VIEW_EVENT = new ShowRegistrationViewEvent();
    @FXML
    private JFXButton login4;
    @FXML
    private JFXButton login3;
    @FXML
    private JFXButton login2;
    @FXML
    private JFXButton login1;

    @FXML
    private JFXPasswordField passwordField;

    @FXML
    private JFXTextField loginField;

    /**
     * Method called when the login button is pressed
     * <p>
     * This Method is called when the login button is pressed. It takes the text
     * entered in the login and password field and gives the user service a request
     * to log in the user specified by those fields.
     *
     * @param event the ActionEvent generated by pressing the login button
     * @see de.uol.swp.client.user.UserService
     * @since 2019-08-13
     */
    @FXML
    private void onLoginButtonPressed(ActionEvent event) {
        userService.login(loginField.getText(), passwordField.getText());
    }

    /**
     * Method called when the register button is pressed
     * <p>
     * This Method is called when the register button is pressed. It posts an instance
     * of the ShowRegistrationViewEvent to the EventBus the SceneManager is subscribed
     * to.
     *
     * @param event the ActionEvent generated by pressing the register button
     * @see de.uol.swp.client.register.event.ShowRegistrationViewEvent
     * @see de.uol.swp.client.SceneManager
     * @since 2019-08-13
     */
    @FXML
    private void onRegisterButtonPressed(ActionEvent event) {
        eventBus.post(SHOW_REGISTRATION_VIEW_EVENT);
    }

    /**
     * The text field is made empty in the LoginPresenter
     *
     * @param msg return to login
     * @see ShowLoginViewEvent
     */

    @Subscribe
    public void onLoginButtonPressed(ShowLoginViewEvent msg) {
        passwordField.clear();
        loginField.clear();
    }
}
